apps/accounts/urls.py
from django.urls import path
from .views.settings_views import AccountSettings


urlpatterns = [
    path("settings/", AccountSettings.as_view(), name="account_settings"),
]

apps/auth/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import user_register


urlpatterns = [
    path("login/", auth_views.LoginView.as_view(template_name="accounts/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("register/", user_register, name="register"),
]

quiz/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(("apps.game.urls", "apps.game"), namespace="quiz")),
    path("accounts/", include(("apps.accounts.urls", "apps.accounts"), namespace="accounts")),
    path("auth/", include(("apps.authentication.urls", "apps.authentication"), namespace="authentication")),
    path("payments/", include(("apps.payments.urls", "apps.payments"), namespace="payments")),
]

# custom 404 page handler
handler404 = "quiz.views.error_404"

apps/authentication/forms/register_forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.hashers import make_password


class UserRegisterForm(forms.Form):
    """User Register form which will be used in a Register FormView."""

    first_name = forms.CharField(label="First Name")
    last_name = forms.CharField(label="Last Name")

    email = forms.EmailField(label="Email")
    username = forms.CharField(label="Username")

    password = forms.CharField(
        label="Password",
        strip=False,
        widget=forms.PasswordInput(),
    )
    confirm_password = forms.CharField(
        label="Confirm Password",
        strip=False,
        widget=forms.PasswordInput(),
    )

    def clean(self):
        """Overwriting clean method which and expanding functionlity to check:
        - if username is taken
        - if provided password and confirm_password fields have same value
        """

        cleaned_data = super().clean()

        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        # check if username is already taken
        user = User.objects.filter(username=cleaned_data.get("username"))
        if user:
            self.add_error("username", "That username is already taken.")

        # check if the password is set correctly and that both values are the same
        if password != confirm_password:
            msg = "Password and Confirm Password should be the same value."
            self.add_error("password", msg)
            self.add_error("confirm_password", msg)

    def save(self):
        """Save method which will store form information in the database, and
        with that it will create a new User object.
        """

        cleaned_data = self.cleaned_data

        # create a new user object with form information
        # also using make_password to hash password information correctly
        user = User(
            username=cleaned_data.get("username"),
            email=cleaned_data.get("email"),
            password=make_password(cleaned_data.get("password")),
            first_name=cleaned_data.get("first_name"),
            last_name=cleaned_data.get("last_name"),
        )
        # set user as active
        user.is_active = True

        # store user information
        user.save()

apps/accounts/views/settings_views.py
from django.views.generic import TemplateView
from apps.authentication.forms.change_password_forms import ChangePasswordForm
from apps.authentication.forms.basic_user_information_forms import BasicUserInformationForm
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


@method_decorator(login_required, name="dispatch")
class AccountSettings(TemplateView):
    template_name = "accounts/settings.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # get user from the request
        user = self.request.user

        # set user in the context
        context["user"] = user

        # set change password form in the context
        context["change_password_form"] = ChangePasswordForm()

        # prefil basic user information with the data which we have in the DB, and add it into context
        context["basic_user_information_form"] = BasicUserInformationForm(
            {
                "first_name": user.first_name,
                "last_name": user.last_name,
                "email": user.email,
            }
        )

        # return context
        return context

apps/authentication/views/register_views.py
from django.shortcuts import redirect, render

from django.views.generic import FormView
from ..forms.register_forms import UserRegisterForm


class UserRegisterView(FormView):
    template_name = "authentication/register.html"
    form_class = UserRegisterForm
    success_url = "/auth/login"

    def post(self, request, *args, **kwargs):
        """Post method - will handle incoming POST request which will have all
        the form data.
        It will validate form information and if everything is good it will
        trigger .save() method which will create a new User in the database.
        """

        # get current form instance which is defined by the form_class
        form = self.get_form()

        if form.is_valid():
            # create new user with the appropriate data
            form.save()

            # redirect user on the login screen
            return redirect(self.success_url)

        else:
            # handling invalid form data (when validation fails)
            # will render the form again with the error information
            return render(self.request, self.template_name, context=self.get_context_data())

templates/accounts/login.html
{% extends "base.html" %}

{% load static %}
{% block extra_styles %}
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/login.css' %}">
{% endblock %}

{% block content %}

    <div class="d-flex justify-content-center login">
        <div class="card card-container">
            <h2>Login</h2>
            <form method="post" action="{% url 'accounts:login' %}" class="form-signin">
                {% csrf_token %}
                <div class="item">
                    <span>{{ form.username.label_tag }}</span>
                    {{ form.username }}
                </div>

                <div class="item">
                    <span>{{ form.password.label_tag }}</span>
                    {{ form.password }}
                </div>

                <button class="btn btn-lg btn-primary btn-block btn-signin" type="submit">Sign in</button>
                <input type="hidden" name="next" value="{{ next }}">
               
            </form><!-- /form -->
        </div>
    </div>

    {% if form.errors %}
        <div class="d-flex justify-content-center login alert alert-danger">
            <p class="error" >Your username and password didn't match. Please try again.</p>
        </div>
    {% endif %}

{% endblock %}

templates/accounts/register.html
{% extends "base.html" %}

{% load static %}
{% block extra_styles %}
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/login.css' %}">
{% endblock %}

{% block content %}

    <div class="d-flex justify-content-center login">
        <div class="card card-container">
            <h2>Register</h2>
            <form method="post" action="{% url 'accounts:register' %}" class="form-signin">
                {% csrf_token %}

                <div class="form-group">
                    <label for="req-username-input">Username</label>
                    <input type="text" class="form-control" id="req-username-input" placeholder="Enter username">
                </div>
                <div class="form-group">
                    <label for="req-password-input">Password</label>
                    <input type="password" class="form-control" id="req-password-input" placeholder="Password">
                </div>
                <div class="form-group">
                    <label for="req-re-password-input">Repeat Password</label>
                    <input type="password" class="form-control" id="req-re-password-input" placeholder="Password">
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
               
            </form><!-- /form -->
        </div>
    </div>

    {% if error_message %}
        <div class="d-flex justify-content-center login alert alert-danger">
            <p class="error" >{{ error_message }}</p>
        </div>
    {% endif %}

{% endblock %}