apps/accounts/urls.py
from django.urls import path
from .views.settings_views import AccountSettings


urlpatterns = [
    path("settings/", AccountSettings.as_view(), name="account_settings"),
]

apps/authentication/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views.register_views import UserRegisterView
from .views.user_info_update_views import UserPasswordChangeView, UserBasicInformationChangeView

urlpatterns = [
    # use django authentication login view
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="authentication/login.html", redirect_authenticated_user=True),
        name="login",
    ),
    # use django authentaication logout view
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("register/", UserRegisterView.as_view(), name="register"),
    path("change-password/", UserPasswordChangeView.as_view(), name="change_password"),
    path("change-basic/", UserBasicInformationChangeView.as_view(), name="change_basic_information"),
]

quiz/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(("apps.game.urls", "apps.game"), namespace="quiz")),
    path("accounts/", include(("apps.accounts.urls", "apps.accounts"), namespace="accounts")),
    path("auth/", include(("apps.authentication.urls", "apps.authentication"), namespace="authentication")),
    path("payments/", include(("apps.payments.urls", "apps.payments"), namespace="payments")),
]

# custom 404 page handler
handler404 = "quiz.views.error_404"

apps/accounts/views/settings_views.py
from django.views.generic import TemplateView
from apps.authentication.forms.change_password_forms import ChangePasswordForm
from apps.authentication.forms.basic_user_information_forms import BasicUserInformationForm
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


@method_decorator(login_required, name="dispatch")
class AccountSettings(TemplateView):
    template_name = "accounts/settings.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # get user from the request
        user = self.request.user

        # set user in the context
        context["user"] = user

        # set change password form in the context
        context["change_password_form"] = ChangePasswordForm()

        # prefil basic user information with the data which we have in the DB, and add it into context
        context["basic_user_information_form"] = BasicUserInformationForm(
            {
                "first_name": user.first_name,
                "last_name": user.last_name,
                "email": user.email,
            }
        )

        # return context
        return context

apps/accounts/templates/accounts/settings.html
{% extends 'base.html'%}

{% load static %}

{% block extra_styles %}
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/style.css' %}">
{% endblock %}


{% block title %} Quiz - Settings {% endblock %}


{% block content %}
    <div class="row justify-content-center margin-top-base" id="settings">

        <div class="row messages">
            <div class="col-12 col-lg-10 col-xl-8 mx-auto">
                {% if messages %}
                    <div class="message-data">
                        {% for message in messages %}
                            <span class="alert alert-{{ message.tags }}">{{ message }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
        </div>

        <div class="row">
            <div class="col-12 col-lg-10 col-xl-8 mx-auto">
                <h2 class="h3 mb-4 page-title">Settings</h2>
                <div class="my-4" id="basic-user-info-change">
                    <h5 class="mb-0 mt-5">User Account Settings</h5>
                    <p>Change your information.</p>
                    <hr class="my-4" />
                    <strong class="mb-0">Required information</strong>
                    <div class="list-group mb-5 shadow">
                        <div class="list-group-item">
                            <div class="row align-items-center">
                                <div class="item">
                                    <span>Username:</span> {{ user.username }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div>
                    <strong class="mb-0">Personal Information</strong>
                    <div class="list-group mb-5 shadow">
                        <div class="list-group-item">
                            <div class="row align-items-center" id="personal-information">
                                <form method="post" action="{% url 'authentication:change_basic_information' %}" class="form-settings">
                                    {% csrf_token %}
                                    {% for field in basic_user_information_form %}
                                        <div class="form-group">
                                            <label for="{{field.id_for_label}}">{{ field.label_tag }}</label>
                                            {{ field }}
        
                                        </div>
                                    {% endfor %}
                                    
                                    <button class="btn btn-primary btn-block" type="submit">Change Personal Information</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>

                <div>
                    <strong class="mb-0">Password Change</strong>
                    <div class="list-group mb-5 shadow" id="password-change">
                        <div class="list-group-item">
                            <div class="row align-items-center">
                                <form method="post" action="{% url 'authentication:change_password' %}" class="form-settings">
                                    {% csrf_token %}
                                    {% for field in change_password_form %}
                                        <div class="item">
                                            <span>{{ field.label_tag }}</span>
                                            {{ field }}

                                        </div>
                                    {% endfor %}

                                    <button class="btn btn-primary btn-block" type="submit">Change Password</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}