apps/accounts/urls.py
from django.urls import path
from .views.settings_views import AccountSettings


urlpatterns = [
    path("settings/", AccountSettings.as_view(), name="account_settings"),
]

apps/auth/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import user_register


urlpatterns = [
    path("login/", auth_views.LoginView.as_view(template_name="accounts/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("register/", user_register, name="register"),
]

apps/game/urls.py
from django.urls import path
from .views import GameIndexView
from .views.quiz_views import QuizGameView
from .views.quiz_question_views import QuizQuestionView
from .views.quiz_index_views import QuizIndexView

urlpatterns = [
    path("", GameIndexView.as_view(), name="index"),
    path("quiz/", QuizIndexView.as_view(), name="quiz_list_index"),
    path("quiz/<pk>/", QuizGameView.as_view(), name="quiz_start"),
    path("quiz/question/<pk>/", QuizQuestionView.as_view(), name="quiz_question"),
]

apps/payments/urls.py
from django.urls import path
from .views.checkout_views import CheckoutSession
from .views.success_views import PaymentSuccessView
from .views.webhook_views import StripeWebhook


urlpatterns = [
    path("webhook/", StripeWebhook.as_view(), name="stripe_webhook"),
    path("success/", PaymentSuccessView.as_view(), name="success"),
    path("checkout/", CheckoutSession.as_view(), name="stripe_checkout"),
]

quiz/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(("apps.game.urls", "apps.game"), namespace="quiz")),
    path("accounts/", include(("apps.accounts.urls", "apps.accounts"), namespace="accounts")),
    path("auth/", include(("apps.authentication.urls", "apps.authentication"), namespace="authentication")),
    path("payments/", include(("apps.payments.urls", "apps.payments"), namespace="payments")),
]

# custom 404 page handler
handler404 = "quiz.views.error_404"

templates/common/site_header.html
<header class="p-3 bg-dark text-white" id="header-nav">
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
        <div class="container-fluid"> 
            
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#main-navbar" aria-controls="main-navbar" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="main-navbar">
                <ul class="navbar-nav me-auto mb-2 mb-sm-0">
                    <li><a href="{% url 'quiz:index' %}" class="nav-link px-2 text-white" id="nav-index">Home</a></li>
                    <li><a href="{% url 'quiz:quiz_list_index' %}" class="nav-link px-2 text-white" id="nav-quiz">Quiz</a></li>
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'payments:stripe_checkout' %}" class="nav-link px-2 text-white" id="nav-donate">Donate</a></li>
                    {% endif %}
                </ul>

                <div class="pull-right">
                    {% if not user.is_authenticated %}
                        <a class="btn btn-outline-light me-2" href="{% url 'authentication:login' %}" role="button">Login</a>
                        <a class="btn btn-warning" href="{% url 'authentication:register' %}" role="button">Register</a>
                    {% endif %}
                    <ul class="navbar-nav col-auto mb-2 mb-sm-0 pull-right">
                        {% if user.is_authenticated %}
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="dropdown03" data-bs-toggle="dropdown" aria-expanded="false">
                                    <span class="user-icon"><i class="fas fa-user-circle"></i></span>{{user.username}}
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="dropdown03">
                                    <li><a class="dropdown-item" href="{% url 'accounts:account_settings' %}">Settings</a></li>
                                    {% if user.is_authenticated and user.is_staff %}
                                        <li><a class="dropdown-item" href="/admin/">Admin</a></li>
                                    {% endif %}
                                    <li><a class="dropdown-item" href="{% url 'authentication:logout' %}">Logout</a></li>
                                </ul>
                            </li>
                        {% endif %}
                    </ul>
                </div>
                
            </div>
        </div>
    </nav>

</header>