apps/game/urls.py
from django.urls import path
from .views import GameIndexView
from .views.quiz_views import QuizGameView
from .views.quiz_question_views import QuizQuestionView
from .views.quiz_index_views import QuizIndexView

urlpatterns = [
    path("", GameIndexView.as_view(), name="index"),
    path("quiz/", QuizIndexView.as_view(), name="quiz_list_index"),
    path("quiz/<pk>/", QuizGameView.as_view(), name="quiz_start"),
    path("quiz/question/<pk>/", QuizQuestionView.as_view(), name="quiz_question"),
]

quiz/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(("apps.game.urls", "apps.game"), namespace="quiz")),
    path("accounts/", include(("apps.accounts.urls", "apps.accounts"), namespace="accounts")),
    path("auth/", include(("apps.authentication.urls", "apps.authentication"), namespace="authentication")),
    path("payments/", include(("apps.payments.urls", "apps.payments"), namespace="payments")),
]

# custom 404 page handler
handler404 = "quiz.views.error_404"

apps/game/models/answer_models.py
from django.db import models
from django.contrib.auth.models import User


class Answer(models.Model):
    """Basic Answer model.
    This model has only the answer text and is_correct field from which admin can define if the
    Answer is correct or not.
    """

    def __str__(self) -> str:
        return self.answer

    question = models.ForeignKey("Question", on_delete=models.CASCADE, related_name="answers")
    answer = models.TextField()
    is_correct = models.BooleanField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, db_index=True)


class SelectedAnswer(models.Model):
    """Model for storing users answers based on the question and the quiz
    itslef.
    """

    def __str__(self):
        return self.content

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    quiz = models.ForeignKey("Quiz", on_delete=models.CASCADE)
    question = models.ForeignKey("Question", on_delete=models.CASCADE)

    content = models.CharField(max_length=256)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, db_index=True)

apps/game/models/question_models.py
from django.db import models


class Question(models.Model):
    """Basic Question model.
    Question has many answers but only one or more of them can be true.
    """

    def __str__(self):
        return self.title

    title = models.CharField(max_length=512)
    description = models.TextField()
    image = models.ImageField(blank=True, null=True)

    quiz = models.ForeignKey("Quiz", on_delete=models.CASCADE, related_name="questions")

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, db_index=True)

apps/game/models/quiz_models.py
from django.db import models
from django.contrib.auth.models import User


class Quiz(models.Model):
    """Base Quiz model. Staff member or some other subscription user will be able to create a new quiz."""

    def __str__(self):
        return self.title

    title = models.CharField(max_length=512)
    description = models.TextField()

    score = models.IntegerField(default=0)

    published = models.DateTimeField(blank=True, null=True)
    is_active = models.BooleanField(default=False)

    valid_from = models.DateTimeField(blank=True, null=True)
    valid_to = models.DateTimeField(blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, db_index=True)

    class Meta:
        # define better plural name on the admin view
        verbose_name_plural = "Quizes"


class QuizTaken(models.Model):
    """Model which will store quiz which user took. With this we are adding possibility to show
    dashboard information about quizes for each user.
    """

    # status choices for quiz taken
    STATUS_STARTED = "STARTED"
    STATUS_PAUSED = "PAUSED"
    STATUS_FINISHED = "FINISHED"

    STATUS_CHOICES = ((STATUS_STARTED, "Started"), (STATUS_PAUSED, "Paused"), (STATUS_FINISHED, "Finished"))

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    quiz = models.ForeignKey("Quiz", on_delete=models.CASCADE, related_name="user_quizes")

    status = models.CharField(max_length=256, choices=STATUS_CHOICES, default=STATUS_STARTED)
    score = models.IntegerField(default=0)

    started_at = models.DateTimeField(blank=True, null=True)
    finished_at = models.DateTimeField(blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, db_index=True)

    class Meta:
        # define better plural name on the admin view
        verbose_name_plural = "Quizes Taken"

apps/game/views/quiz_index_views.py
from django.views.generic import ListView
from ..models.quiz_models import Quiz
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


@method_decorator(login_required, name="dispatch")
class QuizIndexView(ListView):
    model = Quiz
    template_name = "game/quiz/quiz_list.html"

    def get_context_data(self, **kwargs):
        # get base context
        context = super().get_context_data(**kwargs)

        # get all of the quiz objects
        quizes = self.model.objects.all()

        # if there are quiz objects return all of them, otherwise send error message
        if quizes:
            context["quizes"] = self.model.objects.all()
        else:
            context[
                "error_message"
            ] = "There are no quizes at this moment. Please wait until new ones are created or approved."

        # return context
        return context

apps/game/views/quiz_question_views.py
from django.urls.base import reverse
from django.views.generic import DetailView
from ..models.quiz_models import Quiz
from ..models.question_models import Question
from ..models.answer_models import SelectedAnswer
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


@method_decorator(login_required, name="dispatch")
class QuizQuestionView(DetailView):
    model = Question

    def post(self, request, pk):
        # get question object based on the id
        question = self.model.objects.get(id=pk)

        # get quiz id from the fields in the form
        quiz_id = self.request.POST["quiz"]
        quiz = Quiz.objects.get(id=quiz_id)

        # get choice_id from the values on the form
        choice_id = self.request.POST.get("choice")
        user = request.user

        selected_answer_choice = None

        # if there is no choice redirect back to quiz start
        if not choice_id:
            return redirect(reverse("quiz:quiz_start", args=(quiz.id,)))

        # try to get selected answer choice
        try:
            selected_answer_choice = question.answers.get(id=choice_id)
        except Exception:
            pass

        if selected_answer_choice and quiz and user:
            # create new Selecte Answer or update existing one, if it is the Answer to the same Question
            ob, created = SelectedAnswer.objects.update_or_create(
                user=user,
                quiz=quiz,
                question=question,
                defaults={
                    "content": selected_answer_choice.answer,
                },
            )

        # return redirect response to the quiz
        return redirect(reverse("quiz:quiz_start", args=(quiz.id,)))

apps/game/views/quiz_views.py
from django.views.generic import DetailView
from ..models.quiz_models import Quiz, QuizTaken
from ..models.question_models import Question
from ..models.answer_models import SelectedAnswer
from django.shortcuts import render
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


class QuizStatus:
    def __init__(self, quiz_taken) -> None:
        self._quiz_taken = quiz_taken

    def is_started(self):
        """Method to check if user has already started this particular quiz."""

        quiz_already_started = False
        # check if quiz is already started - if it is then set up already_started bool
        quiz_taken = self._quiz_taken

        if quiz_taken:
            quiz_already_started = True

        return quiz_already_started

    def is_completed(self, questions_list):
        """Method to check if all the questions had been answered in the quiz."""

        answered_qustions = 0
        correct_answers = 0
        # iterate through all of the questions
        for item in questions_list:
            if item.get("selected_answer_for_this_question"):
                answered_qustions += 1
            if item.get("answer_is_correct"):
                correct_answers += 1
        # compare counters
        if len(questions_list) == answered_qustions:
            return True, correct_answers
        return False, correct_answers


class GameQuiz:
    def __init__(self, user, quiz):
        self._user = user
        self._quiz = quiz

    def _get_quiz_taken(self):
        """Method to return taken quiz for this user"""

        quiz_taken = QuizTaken.objects.filter(user=self._user, quiz=self._quiz)
        return quiz_taken

    def start(self):
        """Method to start a new quiz for the user, it will create an entry in the QuizTaken model."""

        # start quiz for this user - create a QuizTaken object or update
        quiz_taken, created = QuizTaken.objects.update_or_create(
            user=self._user,
            quiz=self._quiz,
            defaults={
                "status": QuizTaken.STATUS_STARTED,
            },
        )
        # check if object is created, if created set started_at at now()
        if created:
            quiz_taken.started_at = timezone.now()
            quiz_taken.save()

        return True

    def restart(self):
        """Method to restart quiz."""

        quiz_taken = self._get_quiz_taken()
        questions = Question.objects.filter(quiz=self._quiz)
        for question in questions:
            selected_answer = SelectedAnswer.objects.filter(user=self._user, quiz=self._quiz, question=question)
            selected_answer.delete()
        quiz_taken.delete()

        return self._get_quiz_taken()

    @property
    def status(self):
        """Property which will return QuizStatus object on the output, from which we can extract is_started and
        is_completed methods.
        """

        status = QuizStatus(quiz_taken=self._get_quiz_taken())
        return status


@method_decorator(login_required, name="dispatch")
class QuizGameView(DetailView):
    model = Quiz
    template_name = "game/quiz.html"

    def _get_selected_answer(self, question, quiz):
        """Function to get all the selected answers for question and quiz."""

        # get selected answer object
        selected_answer = SelectedAnswer.objects.filter(user=self.request.user, quiz=quiz, question=question).first()

        return selected_answer

    def _get_questions_list(self, quiz):
        """Function to get all the questions/answers and few additional variables."""

        questions_list = list()
        # iterate through quiz questions
        for question in quiz.questions.all():
            selected_answer = self._get_selected_answer(question=question, quiz=quiz)

            answer_is_correct = False
            # if there is selected answer - check if that answer is correct
            if selected_answer:
                correct_answer = question.answers.filter(is_correct=True).first()
                if correct_answer and correct_answer.answer == selected_answer.content:
                    answer_is_correct = True

            # prepare all the required data
            data = {
                "question": question,
                "answers": question.answers.all(),
                "selected_answer_for_this_question": selected_answer,
                "answer_is_correct": answer_is_correct,
            }
            # append data to list
            questions_list.append(data)

        return questions_list

    def get(self, request, pk):
        quiz = None
        try:
            # get quiz object
            quiz = self.model.objects.get(id=pk, is_active=True)
        except Exception:
            return render(self.request, template_name="common/errors/http_404.html", context={})

        # return 404 if there is no quiz object for the particular id
        if quiz:
            # game quiz
            quiz_game = GameQuiz(user=self.request.user, quiz=quiz)

            # check if quiz is started
            quiz_started = quiz_game.status.is_started()

            if self.request.GET.get("option") and self.request.GET["option"] == "start":
                # start new quiz
                quiz_started = quiz_game.start()
            elif self.request.GET.get("option") and self.request.GET["option"] == "restart":
                # delete old quiz for the user and start a new one
                quiz_started = quiz_game.restart()

            questions_list = self._get_questions_list(quiz=quiz)
            quiz_completed, answered_correctly_count = quiz_game.status.is_completed(questions_list=questions_list)

            # if quiz is completed render completed template
            if quiz_completed:
                context = {
                    "quiz": quiz,
                    "answered_correctly_count": answered_correctly_count,
                    "questions_count": len(questions_list),
                }

                return render(self.request, template_name="game/quiz/quiz_completed.html", context=context)

            # define context to be sent to template
            context = {
                "quiz_object": quiz,
                "questions_list": questions_list,
                "started": quiz_started,
                "quiz_completed": False,
            }
            return render(self.request, template_name=self.template_name, context=context)

        return render(self.request, template_name="common/errors/http_404.html", context={})

quiz/views.py
from django.shortcuts import render


# Defining custom 404 page which will be displayed when DEBUG is set to False (Production environment)
def error_404(request, exception):
    return render(request, "common/errors/http_404.html", status=404)

apps/game/templates/game/quiz/quiz_completed.html
{% extends 'base.html'%}

{% load static %}
{% block extra_styles %}
    <link rel="stylesheet" type="text/css" href="{% static 'game/css/style.css' %}">
{% endblock %}

{% block content %}
    <div class="d-flex justify-content-center margin-top-base" id="quiz-completed">
        <div class="card" id="quiz-start">
            <div class="checkmark-wrapper" style="border-radius:200px; height:200px; width:200px; background: #F8FAF5; margin:0 auto;">
                <i class="checkmark">✓</i>
            </div>
            <div class="card-body">
                <h6 class="card-subtitle mb-2 text-muted">Your score: {{ answered_correctly_count }}/{{ questions_count}}</h6>
                <p class="card-text">Congratulations, you finished quiz <b>{{quiz.title}}</b>.</p>
            </div>
            <a class="btn btn-primary quiz-start-btn" href="{% url 'quiz:quiz_start' quiz.id %}?option=restart" role="button">Restart Quiz</a>
        </div>
    </div>
{% endblock %}

apps/game/templates/game/quiz/quiz_description.html
<div class="d-flex justify-content-center" id="quiz-description">
    <div class="card" id="quiz-start">
        <div class="card-body">
            <h5 class="card-title">{{quiz_object.title}}</h5>
            <h6 class="card-subtitle mb-2 text-muted">Max possible points: {{quiz_object.score}}</h6>
            <p class="card-text">{{quiz_object.description}}</p>
        </div>
        <div class="d-grid d-md-block button-wrapper" style="padding: 10px;">
            <a class="btn btn-primary" href="{% url 'quiz:quiz_start' quiz_object.id %}?option=start" role="button">Start Quiz</a>
        </div>
        
    </div>
</div>

apps/game/templates/game/quiz/quiz_list.html
{% extends 'base.html'%}

{% load static %}
{% block extra_styles %}
    <link rel="stylesheet" type="text/css" href="{% static 'game/css/style.css' %}">
{% endblock %}

{% block content %}
    {% if quizes %}
        <div class="d-flex justify-content-center margin-top-base" id="quiz-completed">
            {% for quiz in quizes %}
                <div class="card quiz-list-item">
                    <div class="card-body">
                        <h5 class="card-title">{{quiz.title}}</h5>
                        <p class="card-text">{{quiz.description}}</p>
                    </div>
                    <div class="d-grid d-md-block button-wrapper" style="padding: 10px;">
                        <a class="btn btn-primary quiz-start-btn" href="{% url 'quiz:quiz_start' quiz.id %}?option=start" role="button">Start Quiz</a>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <div class="d-flex justify-content-center error-output margin-top-base">
            <div class="alert alert-secondary" role="alert">
                {{ error_message }}
            </div>
        </div>
    {% endif %}
{% endblock %}

apps/game/templates/game/quiz/quiz_questions_display.html
<ul class="list-group margin-top-base" id="question-list">
    {% for question in questions_list %}

        {% if question.selected_answer_for_this_question %}
            <li class="list-group-item">
                <div {% if question.answer_is_correct %} class="row correct" {% else %} class="row" {% endif %}>
                    <form action="{% url 'quiz:quiz_question' question.question.id %}" method="post">
                    {% csrf_token %}
                    <fieldset>
                        <legend><h3>Question: {{ question.question.title }}</h3></legend>
                        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
                        {% for answer in question.answers %}
                            {{ selected_answer_for_this_question.content }}
                            {% if answer.answer in question.selected_answer_for_this_question.content %}
                                <input type="radio" name="choice" id="choice{{ question.question.id }}-{{ forloop.counter }}" value="{{ answer.id }}" checked disabled>
                                <label for="choice{{ question.question.id }}-{{ forloop.counter }}">{{ answer.answer }}</label><br>
                                <input type="hidden" name="quiz" value="{{ quiz_object.id }}"/>
                            {% else %}
                                <input type="radio" name="choice" id="choice{{ question.question.id }}-{{ forloop.counter }}" value="{{ answer.id }}" disabled>
                                <label for="choice{{ question.question.id }}-{{ forloop.counter }}">{{ answer.answer }}</label><br>
                                <input type="hidden" name="quiz" value="{{ quiz_object.id }}" />
                            {% endif %}
                        {% endfor %}
                    </fieldset>

                    <input type="submit" class="btn btn-secondary" disabled value="Answer">
                    </form>
                </div>
            </li>
        {% else %}
            <li class="list-group-item">
                <div class="row">
                    <form action="{% url 'quiz:quiz_question' question.question.id %}" method="post">
                    {% csrf_token %}
                    <fieldset>
                        <legend><h3>Question: {{ question.question.title }}</h3></legend>
                        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
                        {% for answer in question.answers %}
                            <input type="radio" name="choice" id="choice{{ question.question.id }}-{{ forloop.counter }}" value="{{ answer.id }}">
                            <label for="choice{{ question.question.id }}-{{ forloop.counter }}">{{ answer.answer }}</label><br>
                            <input type="hidden" name="quiz" value="{{ quiz_object.id }}" />
                        {% endfor %}
                    </fieldset>

                    <input type="submit" class="btn btn-secondary" value="Answer">
                    </form>
                </div>
            </li>
        {% endif %}

    {% endfor %}
</ul>